stages:
- build

build:
  stage: build
  image: maven:3.3.9-jdk-8
  script: "mvn clean package"
  artifacts:
    name: "EpicFarming"
    paths:
    - "$CI_PROJECT_DIR/target/*.jar"
    - "$CI_PROJECT_DIR/Read_this_before_your_first_use.txt"
